select
   '$$disease_area$$' as disease_area_name,
   medlinecitation.pmid._value as `pmid`,
   parse_nctid(split(parse_nested_list(medlinecitation.article.databanklist.databank.accessionnumberlist.accessionnumber), '\\\|')) as nct_id,
   get_pmc_id(pubmeddata.articleidlist.articleid._value) as pmc_id,
   concat_ws('|', pubmeddata.articleidlist.articleid._value) as `articleid`,
   concat_ws('|', medlinecitation.article.articledate.day) as `article_day`,
   concat_ws('|', medlinecitation.article.articledate._datetype) as `articledate_date_type`,
   concat_ws('|', medlinecitation.article.articledate.month) as `article_month`,
   concat_ws('|', medlinecitation.article.articledate.year) as `article_year`,
   medlinecitation.article.articletitle._value as `articletitle`,
   medlinecitation.article.articletitle._book as `articletitle_book`,
   medlinecitation.article.articletitle._part as `articletitle_part`,
   medlinecitation.article.articletitle._sec as `articletitle_sec`,
   concat_ws('|', medlinecitation.article.authorlist.author.initials) as `author_initials`,
   concat_list('|', medlinecitation.article.authorlist.author.lastname) as `author_lastname`,
   medlinecitation.article.authorlist._completeyn as `author_completeyn`,
   medlinecitation.article.authorlist._type as `author_type`,
   concat_ws('|', medlinecitation.article.elocationid._eidtype) as `elocationid_eidtype`,
   concat_ws('|', medlinecitation.article.elocationid._value) as `elocationid`,
   concat_ws('|', medlinecitation.article.elocationid._validyn) as `elocationid_validyn`,
   medlinecitation.article.journal.issn._issntype as `issn_issntype`,
   medlinecitation.article.journal.issn._value as `issn`,
   medlinecitation.article.journal.isoabbreviation as `isoabbreviation`,
   medlinecitation.article.journal.journalissue._citedmedium as `journal_citedmedium`,
   medlinecitation.article.journal.journalissue.volume as `journal_volume`,
   medlinecitation.article.journal.journalissue.issue as `journal_issue`,
   medlinecitation.article.journal.journalissue.pubdate.day as `journal_day`,
   medlinecitation.article.journal.journalissue.pubdate.month as `journal_month`,
   medlinecitation.article.journal.journalissue.pubdate.year as `journal_year`,
   medlinecitation.article.journal.journalissue.pubdate.season as `journal_season`,
   medlinecitation.article.journal.journalissue.pubdate.medlinedate as `journal_medlinedate`,
   medlinecitation.article.journal.title as `journal_title`,
   concat_ws('|', medlinecitation.article.language) as `article_language`,
   concat_ws('|', medlinecitation.article.publicationtypelist.publicationtype._value) as `publicationtype`,
   medlinecitation.daterevised.day as `daterevised_day`,
   medlinecitation.daterevised.month as `daterevised_month`,
   medlinecitation.daterevised.year as `daterevised_year`,
   concat_ws('|', medlinecitation.medlinejournalinfo.country) as `medlinejournalinfo_country`,
   medlinecitation.medlinejournalinfo.issnlinking as `medlinejournalinfo_issnlinking`,
   medlinecitation.medlinejournalinfo.medlineta as `medlinejournalinfo_medlineta`,
   medlinecitation.medlinejournalinfo.nlmuniqueid as `medlinejournalinfo_nlmuniqueid`,
   medlinecitation.pmid._version as `pmid_version`,
   medlinecitation._status as `medlinecitation_status`,
   pubmeddata.publicationstatus as `publicationstatus`,
   concat_ws('|', pubmeddata.articleidlist.articleid._idtype) as `articleid_idtype`,
   concat_ws('|', pubmeddata.history.pubmedpubdate.day) as `history_day`,
   concat_ws('|', pubmeddata.history.pubmedpubdate.second) as `history_second`,
   concat_ws('|', pubmeddata.history.pubmedpubdate._pubstatus) as `history_pubstatus`,
   concat_ws('|', pubmeddata.history.pubmedpubdate.hour) as `history_hour`,
   concat_ws('|', pubmeddata.history.pubmedpubdate.minute) as `history_minute`,
   concat_ws('|', pubmeddata.history.pubmedpubdate.month) as `history_month`,
   concat_ws('|', pubmeddata.history.pubmedpubdate.year) as `history_year`,
   medlinecitation.article.abstract.copyrightinformation as `article_copyrightinformation`,
   concat_list('|', medlinecitation.article.authorlist.author.collectivename) as `author_collectivename`,
   concat_list('|', medlinecitation.article.authorlist.author.forename) as `author_forename`,
   concat_ws('|', medlinecitation.article.authorlist.author.suffix) as `author_suffix`,
   concat_ws('|', medlinecitation.article.authorlist.author._equalcontrib) as `author_equalcontrib`,
   concat_ws('|', medlinecitation.article.authorlist.author._validyn) as `author_validyn`,
   medlinecitation.article.databanklist._completeyn as `databanklist__completeyn`,
   concat_ws('|', medlinecitation.article.databanklist.databank.databankname) as databankname,
   concat_ws('|', medlinecitation.article.grantlist.grant.acronym) as grant_acronym,
   concat_ws('|', medlinecitation.article.grantlist.grant.agency) as grant_agency,
   medlinecitation.article.grantlist._completeyn as grantlist_completeyn,
   medlinecitation.article.pagination.endpage as `endpage`,
   medlinecitation.article.pagination.startpage as `startpage`,
   concat_ws('|', medlinecitation.article.pagination.medlinepgn) as `medlinepgn`,
   concat_ws('|', medlinecitation.article.publicationtypelist.publicationtype._ui) as publicationtype_ui,
   medlinecitation.article.vernaculartitle as `vernaculartitle`,
   medlinecitation.article._pubmodel as `article_pubmodel`,
   concat_ws('|', medlinecitation.chemicallist.chemical.registrynumber) as `chemical_registrynumber`,
   concat_ws('|', medlinecitation.chemicallist.chemical.nameofsubstance._ui) as `nameofsubstance_ui`,
   concat_ws('|', medlinecitation.chemicallist.chemical.nameofsubstance._value) as `nameofsubstance`,
   concat_ws('|', medlinecitation.citationsubset) as `citationsubset`,
   medlinecitation.coistatement as `coistatement`,
   concat_ws('|', medlinecitation.commentscorrectionslist.commentscorrections.pmid._value) as `pmid_value`,
   concat_ws('|', medlinecitation.commentscorrectionslist.commentscorrections.pmid._version) as `commentscorrections_pmid_version`,
   concat_ws('|', medlinecitation.commentscorrectionslist.commentscorrections.note) as `commentscorrections_note`,
   concat_ws('|', medlinecitation.commentscorrectionslist.commentscorrections.refsource) as `commentscorrections_refsource`,
   concat_ws('|', medlinecitation.commentscorrectionslist.commentscorrections._reftype) as `commentscorrections_reftype`,
   medlinecitation.datecompleted.day as `datecompleted_day`,
   medlinecitation.datecompleted.month as `datecompleted_month`,
   medlinecitation.datecompleted.year as `datecompleted_year`,
   concat_ws('|', medlinecitation.genesymbollist.genesymbol) as `genesymbol`,
   concat_ws('|', medlinecitation.generalnote._owner) as `generalnote_owner`,
   concat_ws('|', medlinecitation.generalnote._value) as `generalnote`,
   concat_ws('|', medlinecitation.investigatorlist.investigator.forename) as `investigator_forename`,
   concat_ws('|', medlinecitation.investigatorlist.investigator.initials) as `investigator_initials`,
   concat_ws('|', medlinecitation.investigatorlist.investigator.lastname) as `investigator_lastname`,
   concat_ws('|', medlinecitation.investigatorlist.investigator.suffix) as `investigator_suffix`,
   concat_ws('|', medlinecitation.investigatorlist.investigator._validyn) as `investigator_validyn`,
   concat_ws('|', medlinecitation.keywordlist._owner) as `keywordlist_owner`,
   concat_ws('|', medlinecitation.meshheadinglist.meshheading.descriptorname._majortopicyn) as `meshheading_majortopicyn`,
   concat_ws('|', medlinecitation.meshheadinglist.meshheading.descriptorname._type) as `meshheading_type`,
   concat_ws('|', medlinecitation.meshheadinglist.meshheading.descriptorname._ui) as `meshheading_ui`,
   concat_ws('|', medlinecitation.meshheadinglist.meshheading.descriptorname._value) as `descriptorname`,
   medlinecitation.numberofreferences as `numberofreferences`,
   concat_ws('|', medlinecitation.otherabstract.copyrightinformation) as `copyrightinformation`,
   concat_ws('|', medlinecitation.otherabstract._language) as `otherabstract_language`,
   concat_ws('|', medlinecitation.otherabstract._type) as `otherabstract_type`,
   concat_ws('|', medlinecitation.otherid._source) as `otherid_source`,
   concat_ws('|', medlinecitation.otherid._value) as `otherid`,
   concat_ws('|', medlinecitation.personalnamesubjectlist.personalnamesubject.forename) as `personalnamesubject_forename`,
   concat_ws('|', medlinecitation.personalnamesubjectlist.personalnamesubject.initials) as `personalnamesubject_initials`,
   concat_ws('|', medlinecitation.personalnamesubjectlist.personalnamesubject.lastname) as `personalnamesubject_lastname`,
   concat_ws('|', medlinecitation.personalnamesubjectlist.personalnamesubject.suffix) as `personalnamesubject_suffix`,
   concat_ws('|', medlinecitation.spaceflightmission) as `spaceflightmission`,
   concat_ws('|', medlinecitation.supplmeshlist.supplmeshname._type) as `supplmeshname_type`,
   concat_ws('|', medlinecitation.supplmeshlist.supplmeshname._ui) as `supplmeshname_ui`,
   concat_ws('|', medlinecitation.supplmeshlist.supplmeshname._value) as `supplmeshname`,
   medlinecitation._indexingmethod as `medlinecitation_indexingmethod`,
   medlinecitation._owner as `medlinecitation_owner`,
   medlinecitation._versiondate as `medlinecitation_versiondate`,
   medlinecitation._versionid as `medlinecitation_versionid`,
   concat_ws('|', medlinecitation.article.abstract.abstracttext._label) as abstracttext_label,
   concat_ws('|', medlinecitation.article.abstract.abstracttext._nlmcategory) as abstracttext_nlmcategory,
   concat_ws('|', medlinecitation.article.abstract.abstracttext._value) as abstracttext,
   medlinecitation.article.abstract.copyrightinformation as abstract_copyrightinformation,
   parse_nested_list(medlinecitation.article.databanklist.databank.accessionnumberlist.accessionnumber) as accession_number,
   '{current_ts}' as load_timestamp
from
   $$table$$
