SELECT
		`$type`                                                                           AS type,
        copyrightNotice                                                                   AS copyright_notice,
		recordUrl 																		  AS record_url,
		drugId 																		  	  AS drug_id,
		drugPrimaryName 																  AS drug_primary_name,
		concat_ws('| ', drugNameSynonyms)                                                 AS drug_name_synonyms,
		globalStatus 																	  AS global_status,
		highestDevelopmentStatus 														  AS highest_development_status,
		concat_ws('| ', regionName)                                                       AS region_name,
		countryCode 																	  AS country_code,
		countryName 																	  AS country_name,
		concat_ws('| ', mechanismOfAction)                                                AS mechanism_of_action,
		diseaseName 																	  AS disease_name,
		companyRelationship 															  AS company_relationship,
		companyId 																		  AS company_id,
		companyName 																	  AS company_name,
		currentDevelopmentStatus 														  AS current_development_status,
		currentStatus 																	  AS current_status,
		highestStatusReached 															  AS highest_status_reached,
        concat_ws('| ',indicationGroup)                                                   AS indication_group,
		updatedDate 																	  AS updated_date,
		yearlaunched																	  AS year_launched,
		subsidiaryActivity																  AS subsidiary_activity,
		parentCompanyId																	  AS parent_company_id,
		parentCompanyName                                                                 AS parent_company_name
from $$table$$