select
       concat_ws('; ', organizationPhoneNumbers) as site_phone_no,
       concat_ws('; ', organizationTrialInvestigators.investigatorId) as investigator_id,
       double_nested_list(organizationTrialInvestigators.trialId) as trials_under_investigator,
       organizationId as site_id,
       organizationTotalPastTrials as site_past_trials_total,
       organizationTotalTrials as site_trials_total,
       organizationName as site_name,
       concat_ws('; ', organizationSupportingUrls) as site_supporting_urls,
       concat_ws('; ', pastTrials) as past_trial_id_list,
       concat_ws('; ', organizationPrimaryInvestigators) as site_primary_investigators_id_list,
       organizationLocation.city as site_location_city,
       organizationLocation.streetAddress as site_location_street,
       organizationLocation.country as site_location_country,
       organizationLocation.state as site_location_state,
       organizationLocation.postcode as site_location_postcode,
       `$type` as type,
       organizationLastTrialStartDate as site_last_trial_start_date,
       concat_ws('; ', ongoingTrials) as site_current_trials_list,
       concat_ws('; ', organizationFaxNumbers) as site_fax_number,
       organizationCountryName as site_country,
       organizationType as site_type,
       concat_ws('; ', organizationRegions) as site_regions,
       concat_ws('; ', organizationAffiliatedInvestigators) as site_affiliated_investigators,
       concat_ws('; ', diseaseHierarchy) as disease_hierarchy,
       concat_ws('; ', organizationDiseaseTypes.name) as site_disease_type_name,
       concat_ws('; ', organizationDiseaseTypes.pastTrials) as site_past_trials_by_disease,
       concat_ws('; ', organizationDiseaseTypes.TotalTrials) as site_total_trials_by_disease,
       organizationTotalOngoingTrials as site_total_ongoing_trials,
       organizationGeoLocation.lat as site_geo_location_lat,
       organizationGeoLocation.lon as site_geo_location_lon,
       copyrightNotice as copyright_notice,
       recordUrl as record_url,
	   concat_ws('; ', orgHierarchyDiseaseTypes.name) as disease_types_name,
	   concat_ws('; ', orgHierarchyDiseaseTypes.ongoingtrials) as disease_types_ongoing_trials,
       concat_ws('; ', orgHierarchyDiseaseTypes.diseaseHierarchy) as disease_types_disease_hierarchy,
       concat_ws('; ', orgHierarchyDiseaseTypes.pastTrials) as disease_types_past_trials,
       concat_ws('; ', orgHierarchyDiseaseTypes.totaltrials) as disease_types_total_trials,
	   concat_ws('; ', orgHierarchyTrialCounts.totalTrials) as trial_counts_total_trials,
	   concat_ws('; ', orgHierarchyTrialCounts.totalOngoingTrials) as trial_counts_total_ongoing_trials,
       concat_ws('; ', orgHierarchyTrialCounts.totalPlannedTrials) as trial_counts_total_planned_trials,
       concat_ws('; ', orgHierarchyTrialCounts.totalCompletedTrials) as trial_counts_total_completed_trials,
       concat_ws('; ', orgHierarchyTrialCounts.totalTerminatedTrials) as trial_counts_total_terminated_trials,
	   updatedDate as last_updated_date,
	   concat_ws('; ',organizationNPI) as organization_NPI,
       concat_ws('; ',organizationGoldenId) as organization_golden_id,
       concat_ws('; ', ongoingStatusTrials.id) as ongoing_status_trials_id,
       concat_ws('; ', ongoingStatusTrials.status) as ongoing_status_trials_status,
       concat_ws('; ', ongoingStatusTrials.phase) as ongoing_status_trials_phase,
       concat_ws('; ',relatedTrials) as organization_related_trials,
       concat_ws('; ',plannedTrials) as organization_planned_trials_id,
       concat_ws('; ',diseaseHierarchy) as organization_disease_hierarchy
 from $$table$$
