SELECT
        trialid                                                                           AS trial_id,
        trialtitle                                                                        AS trial_title,
        trialstatus                                                                       AS trial_status,
        trialphase                                                                        AS trial_phase,
        trialstartdate                                                                    AS start_date,
        trialprimarycompletiondate                                                        AS primary_completion_date,
        concat_ws('| ', trialcountries)                                                   AS trial_countries,
        concat_ws('| ',trialregions)                                                      AS regions,
        concat_ws('| ', trialtherapeuticareas.NAME)                                       AS trial_therapeutic_areas_name,
        concat_ws('| ', trialtherapeuticareas.id)                                         AS trial_therapeutic_areas_id,
        parse_dm_udf(trialtherapeuticareas.trialdiseases, 'id')                           AS trial_diseases_id,
        parse_disease_name(trialtherapeuticareas)                                         AS disease_name,
        parse_ps_udf(trialtherapeuticareas, 'trialPatientSegments', 'id')                 AS patient_segment_id,
        parse_ps_udf(trialtherapeuticareas, 'trialPatientSegments', 'name')               AS patient_segment,
        parse_ps_udf(trialtherapeuticareas, 'trialMeshTerms', 'meshId')                   AS trial_mesh_term_id,
        parse_ps_udf(trialtherapeuticareas, 'trialMeshTerms', 'name')                     AS trial_mesh_term_name,
        parse_ps_udf(trialtherapeuticareas, 'trialIcd9', 'icd9Id')                        AS trial_icd9id,
        parse_ps_udf(trialtherapeuticareas, 'trialIcd9', 'name')                          AS trial_icd9_name,
        parse_ps_udf(trialtherapeuticareas, 'trialIcd10', 'icd10Id')                      AS icd10id,
        parse_ps_udf(trialtherapeuticareas, 'trialIcd10', 'name')                         AS trialicd10_name,
        parse_ps_udf(trialtherapeuticareas, 'trialSnomed', 'snomedId')                    AS trial_snomed_id,
        parse_ps_udf(trialtherapeuticareas, 'trialSnomed', 'name')                        AS trial_snomed_name,
        trialobjective                                                                    AS objective,
        concat_ws('| ', trialnotes.date)                                                  AS trial_date,
        concat_ws('| ', trialnotes.details)                                               AS trial_notes,
        trialinclusioncriteria                                                            AS inclusion_criteria,
        trialexclusioncriteria                                                            AS exclusion_criteria,
        parse_pe(trialprimaryendpoint,'primaryEndpoints','primaryEndpoint')               AS primary_endpoint,
        parse_pe(trialotherendpoint,'otherEndpoints','otherEndpoint')                     AS other_endpoint,
        trialstudydesign                                                                  AS study_design,
        concat_ws('| ', trialstudykeywords)                                               AS study_keywords,
        trialpatientpopulation                                                            AS patient_population_criteria,
        parse_protocolid(trialprotocolids)                                                AS protocol_ids,
        parse_nctid(trialprotocolids)                                                     AS nct_id,
        get_eudract_number(trialprotocolids)                                              AS eudract_number,
        concat_ws('| ', trialsponsors.NAME)                                               AS sponsor_name,
        concat_ws('| ', trialsponsors.type)                                               AS sponsor_type,
        concat_ws('| ', trialprimarydrugstested.drugid)                                   AS primary_drug_id,
        concat_ws('| ', trialprimarydrugstested.drugnameid)                               AS primary_drug_name_id,
        concat_ws('| ', trialprimarydrugstested.drugname)                                 AS primary_tested_drug_name,
        concat_ws('| ', trialprimarydrugstested.drugprimaryname)                          AS primary_drug_name,
        concat_ws('| ', trialprimarydrugstested.drugapprovalstatus)                       AS primary_drug_approval_status,
        parse_arrs_udf(trialprimarydrugstested.drugnames)                                 AS primary_drug_names,
        parse_arrs_udf(trialPrimaryDrugsTested.drugparentnames)                           AS other_primary_tested_parent_names,
        parse_arrs_udf(trialprimarydrugstested.drugtherapeuticclasses)                    AS trial_therapeutic_classes,
        parse_arrs_udf(trialprimarydrugstested.drugtherapeuticclasssynonyms)              AS drug_therapeutic_class_synonyms,
        parse_dm_udf(trialprimarydrugstested.mechanismsofaction, 'directMechanism')       AS mechanism_of_action,
        parse_dm_udf(trialprimarydrugstested.mechanismsofaction, 'mechanismSynonyms')     AS mechanism_synonyms,
        concat_ws('| ',trialotherdrugstested.drugnameid )                                 AS other_drug_name_id,
        concat_ws('| ',trialotherdrugstested.drugname )                                   AS other_drug_name,
        parse_arrs_udf(trialotherdrugstested.drugnames)                                   AS other_drug_names,
        parse_arrs_udf(trialotherdrugstested.drugparentnames)                             AS other_drug_tested_parentnames,
        trialpriorconcurrenttherapy                                                       AS trial_prior_concurrent_therapy,
        concat_ws('| ', trialresults.date)                                                AS results_date,
        concat_ws('| ', trialresults.details)                                             AS results_details,
        parse_arrs_udf(trialinvestigators)                                                AS trialinvestigators,
        trialtargetaccrual                                                                AS target_accrual,
        trialtargetaccrualtext                                                            AS trial_target_accrual_text,
        trialactualaccrual                                                                AS trial_actual_accrual,
        trialactualaccrualtext                                                            AS actual_accrual_text,
        trialprimaryendpointsreported                                                     AS trial_primary_endpoints_reported,
        trialidentifiedsites                                                              AS trial_identified_sites,
        trialreportedsites                                                                AS trial_reported_sites,
        concat_ws('| ',trialsupportingurls)                                               AS trial_supporting_urls,
        concat_ws('| ', trialoutcomes)                                                    AS trial_outcomes,
        trialoutcomedetails                                                               AS trial_outcome_details,
        trialpatientcriteria.minage                                                       AS min_patient_age,
        trialpatientcriteria.maxage                                                       AS max_patient_age,
        trialpatientcriteria.minageunits                                                  AS min_age_units,
        trialpatientcriteria.maxageunits                                                  AS max_age_units,
        trialpatientcriteria.gender                                                       AS patient_gender,
        concat_ws('| ', trialtags)                                                        AS trial_tags,
        concat_ws('| ', trialDctAttributes)                                               AS trial_dct_attributes,
		triallastmodifieddate                                                             AS last_modified_date,
        concat_ws('| ',trialpatientdispositions )                                         AS trial_patient_dispositions,
        concat_ws('| ', trialassociatedcro)                                               AS trial_associated_cro,
        concat_ws('| ', trialCtGovMeshTerms.meshTerm)                                     AS trial_ct_gov_mesh_terms,
        concat_ws('| ', trialCtGovMeshTerms.tag)                                          AS trial_ct_gov_mesh_tags,
        copyrightnotice                                                                   AS copy_right_notice,
        recordurl                                                                         AS record_url,
        trialtreatmentplan                                                                AS trial_treatment_plan,
        trialsource                                                                       AS trial_source,
        trialtiming.actualtrialstartdate                                                  AS actual_trial_start_date,
        trialtiming.actualenrollmentduration                                              AS enrollment_duration,
        trialtiming.anticipatedenrollmentperiodclosedate                                  AS enrollment_close_date,
        trialtiming.actualtreatmentduration                                               AS treatment_duration,
        trialtiming.actualprimarycompletiondate                                           AS actual_primary_completion_date,
        trialtiming.totaltrialduration                                                    AS total_trial_duration,
        trialpatientspersitepermonth                                                      AS trial_patients_per_site_per_month,
        concat_ws('| ', trialprimarydrugstested.drugname)                                 AS drug_name,
        trialreportedsites                                                                AS number_of_sites,
        trialprimaryendpoint.details                                                      AS primary_endpoint_details,
        parse_pe(trialprimaryendpoint,'primaryEndpoints','primaryEndpointGroup')          AS primary_endpoint_group,
        parse_pe(trialprimaryendpoint,'primaryEndpoints','primaryEndpointSubGroup')       AS primary_endpoint_sub_group,
        trialotherendpoint.details                                                        AS other_endpoint_details,
        parse_pe(trialotherendpoint,'otherEndpoints','otherEndpointGroup')                AS other_endpoint_group,
        parse_pe(trialotherendpoint,'otherEndpoints','otherEndpointSubGroup')             AS other_endpoint_sub_group,
        concat_ws('| ', trialinvestigators)                                               AS investigators,
        trialtiming.actualtrialstartdate                                                  AS actual_start_date,
        '$$disease_area$$' 																  AS disease_area_name,
        `$type`                                                                           AS type,
		parse_dm_udf(trialtherapeuticareas.trialdiseases, 'tag')                          AS trial_diseases_tag,
        parse_ps_udf(trialtherapeuticareas, 'trialPatientSegments', 'tag')                AS patient_segment_tag,
        parse_ps_udf(trialtherapeuticareas, 'trialMeshTerms', 'tag')                   	  AS trial_mesh_term_tag,
		trialtiming.anticipatedTrialStartDate           								  AS anticipated_trial_start_date,
		trialtiming.anticipatedEnrollmentDuration       								  AS anticipated_enrollment_duration, 
		trialtiming.actualEnrollmentPeriodCloseDate     								  AS actual_enrollment_period_close_date,    
		trialtiming.anticipatedTreatmentDuration        								  AS anticipated_treatment_duration,
		trialtiming.anticipatedPrimaryCompletionDate    								  AS anticipated_primary_completion_date,
		trialtiming.actualTotalTrialCloseDate           								  AS actual_total_trial_close_date,
		trialtiming.anticipatedTotalTrialCloseDate      								  AS anticipated_total_trial_close_date,
		trialtiming.actualPrimaryEndpointsReported      								  AS actual_primary_endpoints_reported,
		trialtiming.anticipatedPrimaryEndpointsReported 								  AS anticipated_primary_endpoints_reported,
		parse_biomarkers_caption(biomarkers.trialTitle.caption) 						  AS biomarkers_trialtitle,
        parse_biomarkers(biomarkers,"trialTitle","commonUses") 					  		  AS biomarkers_commonuses,
        parse_biomarkers(biomarkers,"trialTitle","synonyms") 						  	  AS biomarkers_synonyms,
        parse_biomarkers_caption(biomarkers.trialExclusionCriteria.caption) 			  AS trial_exclusion_criteria_biomarker,
        parse_biomarkers(biomarkers,"trialExclusionCriteria","commonUses") 		  		  AS trial_exclusion_criteria_commonuses,
        parse_biomarkers(biomarkers,"trialExclusionCriteria","synonyms") 			      AS trial_exclusion_criteria_synonyms,
        parse_biomarkers_caption(biomarkers.trialInclusionCriteria.caption) 			  AS trial_inclusion_criteria_biomarker,
        parse_biomarkers(biomarkers,"trialInclusionCriteria","commonUses") 		  		  AS trial_inclusion_criteria_commonuses,
        parse_biomarkers(biomarkers,"trialInclusionCriteria","synonyms") 			      AS trial_inclusion_criteria_synonyms,
        parse_biomarkers_caption(biomarkers.trialObjective.caption) 					  AS trialobjective_biomarker,
        parse_biomarkers(biomarkers,"trialObjective","commonUses")				          AS trialobjective_commonuses,
        parse_biomarkers(biomarkers,"trialObjective","synonyms") 					  	  AS trialobjective_synonyms,
        parse_biomarkers_caption(biomarkers.trialOtherEndpoint.caption) 				  AS trial_other_endpoint_biomarker,
        parse_biomarkers(biomarkers,"trialOtherEndpoint","commonUses") 			  		  AS trial_other_endpoint_commonuses,
        parse_biomarkers(biomarkers,"trialOtherEndpoint","synonyms") 				      AS trial_other_endpoint_synonyms,
        parse_biomarkers_caption(biomarkers.trialPatientPopulation.caption) 			  AS trial_patient_population_biomarker,
        parse_biomarkers(biomarkers,"trialPatientPopulation","commonUses") 		  		  AS trial_patient_population_commonuses,
        parse_biomarkers(biomarkers,"trialPatientPopulation","synonyms") 			      AS trial_patient_population_synonyms,
        parse_biomarkers_caption(biomarkers.trialPrimaryEndpoint.caption) 			      AS trial_primary_endpoint_biomarker,
        parse_biomarkers(biomarkers,"trialPrimaryEndpoint","commonUses") 			      AS trial_primary_endpoint_commonuses,
        parse_biomarkers(biomarkers,"trialPrimaryEndpoint","synonyms") 			          AS trial_primary_endpoint_synonyms,
        parse_biomarkers_caption(biomarkers.trialResults.caption) 					      AS trial_results_biomarker,
        parse_biomarkers(biomarkers,"trialResults","commonUses") 					      AS trial_results_commonuses,
        parse_biomarkers(biomarkers,"trialResults","synonyms") 					  		  AS trial_results_synonyms,
		concat_ws('| ', bmtOtherDrugsTested.drugId)                                       AS bmt_other_drugs_tested_drugid,
		concat_ws('| ', bmtOtherDrugsTested.drugNameId)                                   AS bmt_other_drugs_tested_drug_name_id,
		concat_ws('| ', bmtOtherDrugsTested.ppDrugNameId)                                 AS bmt_other_drugs_tested_ppdrugnameid,
		concat_ws('| ', bmtOtherDrugsTested.drugName)                                     AS bmt_other_drugs_tested_drugname,
		concat_ws('| ', bmtOtherDrugsTested.bmtDrugId)                                    AS bmt_other_drugs_tested_bmt_drugid,
		concat_ws('| ', bmtOtherDrugsTested.bmtBrandName)                                 AS bmt_other_drugs_tested_brand_name,
		concat_ws('| ', bmtPrimaryDrugsTested.drugId)                                     AS bmt_primary_drugs_tested_drugid,
		concat_ws('| ', bmtPrimaryDrugsTested.drugNameId)                                 AS bmt_primary_drugs_tested_drug_name_id,
		concat_ws('| ', bmtPrimaryDrugsTested.ppDrugNameId)                               AS bmt_primary_drugs_tested_ppdrugnameid,
		concat_ws('| ', bmtPrimaryDrugsTested.drugName)                                   AS bmt_primary_drugs_tested_drugname,
		concat_ws('| ', bmtPrimaryDrugsTested.bmtDrugId)                                  AS bmt_primary_drugs_tested_bmt_drugid,
		concat_ws('| ', bmtPrimaryDrugsTested.bmtBrandName)                               AS bmt_primary_drugs_tested_bmt_brand_name,
		concat_ws('| ', ctGovListedLocations.country)                                     AS ct_gov_listed_locations_country,
		concat_ws('| ', ctGovListedLocations.sitesCount)                                  AS ct_gov_listed_locations_sitescount,
		concat_ws('| ',trialotherdrugstested.drugApprovalStatus)                          AS trial_other_drugs_tested_drugapprovalstatus,
		concat_ws('| ',trialotherdrugstested.drugId)                                      AS trial_other_drugs_tested_drugid,
		concat_ws('| ',trialotherdrugstested.drugPrimaryName)                             AS trial_other_drugs_tested_drug_primary_names,
        parse_arrs_udf(trialotherdrugstested.drugTherapeuticClassSynonyms)                AS trial_other_drugs_tested_drug_therapeutic_class_synonyms,
        parse_dm_udf(trialotherdrugstested.mechanismsofaction, 'directMechanism')         AS trial_other_drugs_tested_drug_mechanism_of_action_directMechanism,
        parse_dm_udf(trialotherdrugstested.mechanismsofaction, 'mechanismSynonyms')       AS trial_other_drugs_tested_drug_mechanism_of_action_mechanismSynonyms,
		parse_arrs_udf(trialotherdrugstested.drugTherapeuticClasses)                      AS trial_other_drugs_tested_drug_therapeutic_classes,
		trialRecordType 																  AS trial_record_type,
		updatedDate																		  AS updated_date,
		concat_ws('| ', trialsponsors.parentCompanyHQCity)                                AS trial_sponsors_parentcompanyhqcity,
		concat_ws('| ', trialsponsors.parentCompanyHQCountry)                             AS trial_sponsors_parentcompanyhqcountry,
		concat_ws('| ', trialsponsors.parentCompanyHQPostCode)                            AS trial_sponsors_parentcompanyhqpostcode,
		concat_ws('| ', trialsponsors.parentCompanyHQState)                               AS trial_sponsors_parentcompanyhqstate,
		concat_ws('| ', trialsponsors.parentCompanyName)                                  AS trial_sponsors_parentcompanyname,
        cast("{current_ts}" AS string)                                                    AS load_timestamp
FROM	$$table$$