SELECT
      '$$disease_area$$' as disease_area_name,
       investigatorId                                   AS investigator_id,
       investigatorFirstName                            AS investigator_first_name,
       investigatorMiddleInitial                        AS investigator_middle_initial,
       investigatorLastName                             AS investigator_last_name,
       investigatorGoldenId                             AS investigator_golden_id,
       concat_ws('| ', investigatorDegrees)             AS investigator_degrees,
       investigatorPrimaryOrganization.type             AS investigator_p_organization_type,
       investigatorPrimaryOrganization.id               AS investigator_p_organization_id,
       investigatorPrimaryOrganization.name             AS investigator_p_organization_name,
       concat_ws('| ', investigatorEmails)              AS investigator_emails,
       concat_ws('| ',investigatorPhoneNumbers)         AS investigator_phone_numbers,
       concat_ws('| ', investigatorFaxes)               AS investigator_faxes,
       investigatorLocation.city                        AS investigator_location_city,
       investigatorLocation.streetAddress               AS investigator_location_street_address,
       investigatorLocation.country                     AS investigator_location_country,
       investigatorLocation.state                       AS investigator_location_state,
       investigatorLocation.postCode                    AS investigator_location_post_code,
       investigatorGeoLocation.lat                      AS investigator_geo_location_lat,
       investigatorGeoLocation.lon                      AS investigator_geo_location_lon,
       parse_trail(investigatorDiseaseTiers.tier)       AS investigator_disease_tier,
       parse_trail(investigatorDiseaseTiers.name)       AS investigator_disease_tiers_name,
       concat_ws('| ', investigatorRegions)             AS investigator_regions,
       concat_ws('| ', investigatorSpecialties)         AS investigator_specialties,
       investigatorLastTrialStartDate                   AS investigator_last_trial_start_date,
       investigatorLastRegulatoryAction.action          AS investigator_last_regulatory_action,
       investigatorLastRegulatoryAction.date            AS investigator_last_regulatory_action_date,
       investigatorLastRegulatoryAction.flag            AS investigator_last_regulatory_action_flag,
       investigatorLastRegulatoryAction.details         AS investigator_last_regulatory_action_details,
       parse_trail(investigatorRegulatoryActionHistory.action)  AS investigator_regulatory_action_history,
       parse_trail(investigatorRegulatoryActionHistory.date)    AS investigator_regulatory_action_history_date,
       parse_trail(investigatorRegulatoryActionHistory.flag)    AS investigator_regulatory_action_history_flag,
       parse_trail(investigatorRegulatoryActionHistory.details) AS investigator_regulatory_action_history_details,
       concat_ws('| ',investigatorSupportingUrls)       AS investigator_supporting_urls,
       parse_trail(ongoingTrials.id)                    AS ongoing_trials_id,
       parse_trail(ongoingTrials.status)                AS ongoing_trials_status,
       parse_trail(ongoingTrials.phase)                 AS ongoing_trials_phase,
       parse_trail(pastTrials.id)                       AS past_trials_id,
       parse_trail(pastTrials.status)                   AS past_trials_status,
       parse_trail(pastTrials.phase)                    AS past_trials_phase,
       concat_ws('| ',sponsorRelationships)             AS sponsor_relationships,
       concat_ws('| ',investigatorAllAffiliatedOrganizationIds) AS investigator_all_affiliated_org_id,
       parse_trail(investigatorTrialOrganizations.organizationId)  AS investigator_trial_organizations_org_id,
       parse_nest_list(investigatorTrialOrganizations.trialId) AS investigator_trial_organizations_trail_id,
       copyrightNotice                                  AS copyright_notice,
       recordURL                                        AS record_url,
       concat_ws('| ',diseaseHierarchy)                 AS disease_hierarchy,
       investigatorNPI                                  AS investigator_npi,
       `$type`                                          AS type
       FROM   $$table$$
