
Insert into audit_information.ctl_dataset_master values (1410,'raw','GLOBOCAN','GLOBOCAN','GLOBOCAN','Clinical','NULL','NULL','NULL','NULL',NULL,'NULL','GLOBOCAN_YYYYMMDD*.csv','N','N','csv',',','Y','N',NULL,'s3','s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/pre-ingestion/GLOBOCON/GLOBOCON_DATA/','NULL',7,'s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/pre-landing/GLOBOCAN/GLOBOCAN_DATA/','/data/landing/GLOBOCAN/GLOBOCAN_DATA/','s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/landing/GLOBOCAN/GLOBOCAN_DATA/','/data/pre-dqm/GLOBOCAN/GLOBOCAN_DATA/','s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/pre-dqm/GLOBOCAN/GLOBOCAN_DATA/','/data/staging/GLOBOCAN/GLOBOCAN_DATA/','s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/staging/GLOBOCAN/GLOBOCAN_DATA/','','s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/staging/GLOBOCAN/GLOBOCAN_DATA/','s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/archive/GLOBOCAN/GLOBOCAN_DATA/','NULL','NULL','NULL','NULL','NULL','sanofi_ctfo_datastore_staging_dev.GLOBOCAN','NULL','NULL','NULL','NULL','NULL','NULL','batch_id,file_id','NULL','NULL','NULL','NULL','NULL','','NULL','Y','latest','NULL','NULL','NULL','NULL','NULL','s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/publish/staging/GLOBOCAN/GLOBOCAN_DATA/','NULL');


Insert into audit_information.ctl_column_metadata values (1398,'GLOBOCON',1410,'Country','string','','','Country',1,'');
Insert into audit_information.ctl_column_metadata values (1399,'GLOBOCON',1410,'age_group','string','','','age_group',2,'');
Insert into audit_information.ctl_column_metadata values (1400,'GLOBOCON',1410,'disease','string','','','disease',3,'');
Insert into audit_information.ctl_column_metadata values (1401,'GLOBOCON',1410,'gender','string','','','gender',4,'');
Insert into audit_information.ctl_column_metadata values (1402,'GLOBOCON',1410,'incidence','integer','','','incidence',5,'');
Insert into audit_information.ctl_column_metadata values (1403,'GLOBOCON',1410,'prevalence','integer','','','prevalence',6,'');
Insert into audit_information.ctl_column_metadata values (1404,'GLOBOCON',1410,'year','string','','','year',7,'');


Insert into audit_information.ctl_dqm_master values (20324,1410,'Domain','Gender','male, female','','','NC','','na17763',now(),'NULL','NULL','0');
Insert into audit_information.ctl_dqm_master values (20325,1410,'NULL','Country','','','','C','','na17763',now(),'NULL','NULL','0');


Insert into audit_information.ctl_cluster_config values (400,'Sanofi-DataEngineering-L1-GLOBOCAN-Monthly-Full','monthly','vpc-002dedeb4c69ac582','subnet-0173fdc9ec7312084','aws-a0199-use1-1a-d-emr-snfi-ctf-GLOBOCAN','us-east-1','emr-5.25.0','r4.2xlarge',NULL,'r4.xlarge',NULL,'SPOT','NULL',NULL,'NULL',3,NULL,'EMR_DefaultRole','aws-a0199-glbl-00-d-rol-snfi-ctf-EMR_EC2_role01','aws-a0199-use1-00-d-kpr-snfi-ctf-emr01','N','Y','{"log_uri": "s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/emrlogs", "applications": [{"Name": "Hive"}, {"Name": "Pig"}, {"Name": "Ganglia"}, {"Name": "Hue"}, {"Name": "Spark"}, {"Name": "Sqoop"}, {"Name": "Hadoop"}, {"Name": "Zeppelin"}, {"Name": "Livy"}, {"Name": "Tez"}, {"Name": "Presto"}], "cluster_tags": [{"Key": "Name", "Value": "aws-a0199-use1-1a-d-emr-snfi-ctf-GLOBOCAN"},{"Key": "ZS_Project_Code", "Value": "9901ZS6157"}],"check_launch_flag": "N", "step_creation_property": [{"Name": "CustomJAR", "HadoopJarStep": {"Jar": "s3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar", "Args": ["s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/python3/emr_step_creation.sh"]}, "ActionOnFailure": "TERMINATE_CLUSTER"}],"termination_on_failure_flag": "N", "termination_on_success_flag": "Y","cc_branch_name": "integration", "dm_branch_name": "integration","hdfs_disk_space":500,"ServiceAccessSecurityGroup": "sg-081cd03adcb10733e", "EmrManagedSlaveSecurityGroup": "sg-0ae266ee04d7cc014", "EmrManagedMasterSecurityGroup": "sg-011a1c64d5af20322", "AdditionalMasterSecurityGroups": "sg-011a1c64d5af20322","security_conf": "aws-a0199-use1-00-d-sec-snfi-ctf-emr02", "cluster_bootstrap_s3_location": "s3://aws-a0199-use1-00-d-s3b-snfi-ctf-data01/clinical-data-lake/code/bootstrap/python3_emr_bootstrap_bitbucket.sh"}',0.378,NULL);


Insert into audit_information.ctl_workflow_master values (1410,'Sanofi-DataEngineering-L1-GLOBOCAN-Monthly-Full',1410,400,'Y','na17763','now()','na17763',current_timestamp(),'{}','--driver-memory 3G --executor-cores 3 --executor-memory 17G --conf spark.driver.allowMultipleContexts=true --conf spark.scheduler.mode=FAIR --conf spark.sql.shuffle.repartitions=500 --conf spark.yarn.executor.memoryOverhead=2000M --conf spark.default.parallelism=700 --conf spark.port.maxRetries=200 --conf spark.rpc.askTimeout=600s --conf spark.network.timeout=10000001');