select
 '$$disease_area$$' as disease_area_name,
 drugId as drugId,
 drugPrimaryName as drugPrimaryName,
 concat_ws('| ', drugNameSynonyms) as drugNameSynonyms,
 overview as overview,
 marketing as marketing,
 licensing as licensing,
 phaseI as phaseI,
 phaseII as phaseII,
 phaseIII as phaseIII,
 preClinical as preClinical,
 globalStatus as globalStatus,
 originatorName as originatorName,
 originatorCountry as originatorCountry,
 originatorStatus as originatorStatus,
 originatorCompanyKey as originatorCompanyKey,
 originatorParentName as originatorParentName,
 originatorParentKey as originatorParentKey,
 concat_ws('| ', licensee.licenseeName) as licensee_licenseeName,
 concat_ws('| ', licensee.licenseeStatus) as licensee_licenseeStatus,
 concat_ws('| ', licensee.licenseeCompanyKey) as licensee_licenseeCompanyKey,
 concat_ws('| ', licensee.licenseeCountry) as licensee_licenseeCountry,
 concat_ws('| ', indicationGroups.id) as indicationGroups_id,
 concat_ws('| ', indicationGroups.name) as indicationGroups_name,
 parse_struct_of_struct(indicationGroups, 'indications', 'diseaseName') as indications_diseaseName,
 parse_struct_of_struct(indicationGroups, 'indications', 'diseaseStatus') as indications_diseaseStatus,
 concat_ws('| ', drugMeshTerms.meshId) as drugMeshTerms_meshId,
 concat_ws('| ', drugMeshTerms.name) as drugMeshTerms_name,
 concat_ws('| ', drugIcd9.icd9Id) as drugIcd9_icd9Id,
 concat_ws('| ', drugIcd9.name) as drugIcd9_name,
 concat_ws('| ', keyEvents.keyEventDate) as keyEvents_keyEventDate,
 concat_ws('| ', keyEvents.keyEventDetail) as keyEvents_keyEventDetail,
 concat_ws('| ', keyEvents.keyEventHistory) as keyEvents_keyEventHistory,
 latestChangeDate as latestChangeDate,
 latestChange as latestChange,
 concat_ws('| ', therapeuticClasses.therapeuticClassName) as therapeuticClasses_therapeuticClassName,
 concat_ws('| ', therapeuticClasses.therapeuticClassStatus) as therapeuticClasses_therapeuticClassStatus,
 concat_ws('| ', mechanismsOfAction) as mechanismsOfAction,
 concat_ws('| ', deliveryRoutes) as deliveryRoutes,
 concat_ws('| ', deliveryMediums) as deliveryMediums,
 concat_ws('| ', deliveryTechnologies) as deliveryTechnologies,
 origin as origin,
 concat_ws('| ', casNumbers) as casNumbers,
 molecularFormula as molecularFormula,
 molecularWeight as molecularWeight,
 nce as nce,
 chemicalName as chemicalName,
 concat_ws('| ', chemicalStructure) as chemicalStructure,
 concat_ws('| ', pharmacokinetics.model) as pharmacokinetics_model,
 concat_ws('| ', pharmacokinetics.unit) as pharmacokinetics_unit,
 concat_ws('| ', pharmacokinetics.parameter) as pharmacokinetics_parameter,
 concat_ws('| ', drugCountries.name) as drugCountries_name,
 concat_ws('| ', drugCountries.status) as drugCountries_status,
 concat_ws('| ', drugCountries.yearLaunched) as drugCountries_yearLaunched,
 concat_ws('| ', drugCountries.licensingOpportunity) as drugCountries_licensingOpportunity,
 concat_ws('| ', patents.patentNumber) as patents_patentNumber,
 concat_ws('| ', patents.patentPriorityCountryDate) as patents_patentPriorityCountryDate,
 concat_ws('| ', targets.targetName) as targets_targetName,
 parse_struct_of_list(targets, 'targetSynonyms') as targets_targetSynonyms,
 concat_ws('| ', targets.entrezGeneId) as targets_entrezGeneId,
 parse_struct_of_list(targets, 'targetFamilies') as targets_targetFamilies,
 parse_struct_of_list(targets, 'targetECNumbers') as targets_targetECNumbers,
 concat_ws('| ', trialIds) as trialIds,
 isPharmaProjectsDrug as isPharmaProjectsDrug,
 drugSource as drugSource,
 copyrightNotice as copyrightNotice,
 recordUrl as recordUrl,
 concat_ws('| ', drugIcd10.icd10Id) as drugIcd10_icd10Id,
 concat_ws('| ', drugIcd10.name) as drugIcd10_name,
 concat_ws('| ', drugSnomed.snomedId) as drugSnomed_snomedId,
 concat_ws('| ', drugSnomed.name) as drugSnomed_name,
 '{current_ts}' as load_timestamp
 from $$table$$
