SELECT
	`$type`                                                                     AS type,
    	copyrightNotice                                                             AS copyright_notice,
	drugId 									    AS drug_id,
	drugPrimaryName																AS drug_primary_name,
	concat_ws('| ',bmtDrug)														AS bmt_drug,
	parse_dm_drug_trends_years(years,"yearValue") 									AS year_value,
	parse_dm_drug_trends_years(years,"globalStatus") 								AS global_status,
	parse_dm_drug_trends_years(years,"drugDevelopmentStatus") 						AS drug_development_status,
	parse_dm_drug_trends_years(years,"originatorCompanyKey") 						AS origintator_company_key,
	parse_dm_drug_trends_years(years,"originatorName") 								AS originator_name,
	parse_dm_drug_trends_years(years,"originatorCountry") 							AS originator_country,
	parse_dm_drug_trends_years(years,"originatorStatus") 							AS originator_status,
	parse_iterate_dict(years,"licensees","licenseeCompanyKey") 				AS licensee_company_key,
	parse_iterate_dict(years,"licensees","licenseeName") 					AS licensee_name,
	parse_iterate_dict(years,"licensees","licenseeStatus") 					AS licensee_status,
	parse_iterate_dict(years,"licensees","licenseeCountry") 				AS licensee_country,
	parse_iterate_dict(years,"countries","countryName") 					AS country_ame,
	parse_iterate_dict(years,"countries","countryStatus") 					AS country_status,
	parse_iterate_dict(years,"countries","yearLaunch") 						AS year_launch,
	parse_iterate_dict(years,"countries","licensingOpportunity") 			AS licensing_opportunity,
	parse_iterate_dict(years,"mechanisms","mechanismsOfAction") 			AS mechanisms_of_action,
	parse_iterate_dict(years,"therapeuticClasses","therapeuticClassName") 	AS therapeutic_class_name,
	parse_iterate_dict(years,"therapeuticClasses","therapeuticClassStatus") AS therapeutic_class_status
from $$table$$