SELECT
        trialid                                                                           AS trial_id,
        trialtitle                                                                        AS trial_title,
        trialstatus                                                                       AS trial_status,
        trialphase                                                                        AS trial_phase,
        trialstartdate                                                                    AS start_date,
        trialprimarycompletiondate                                                        AS primary_completion_date,
        concat_ws('| ', trialcountries)                                                   AS trial_countries,
        concat_ws('| ',trialregions)                                                      AS regions,
        concat_ws('| ', trialtherapeuticareas.NAME)                                       AS trial_therapeutic_areas_name,
        concat_ws('| ', trialtherapeuticareas.id)                                         AS trial_therapeutic_areas_id,
        parse_dm_udf(trialtherapeuticareas.trialdiseases, 'id')                           AS trial_diseases_id,
        parse_disease_name(trialtherapeuticareas)                                         AS disease_name,
        parse_ps_udf(trialtherapeuticareas, 'trialPatientSegments', 'id')                 AS patient_segment_id,
        parse_ps_udf(trialtherapeuticareas, 'trialPatientSegments', 'name')               AS patient_segment,
        parse_ps_udf(trialtherapeuticareas, 'trialMeshTerms', 'meshId')                   AS trial_mesh_term_id,
           parse_ps_udf(trialtherapeuticareas, 'trialMeshTerms', 'name')                     AS trial_mesh_term_name,
                   parse_ps_udf(trialtherapeuticareas, 'trialIcd9', 'icd9Id')                        AS trial_icd9id,
                   parse_ps_udf(trialtherapeuticareas, 'trialIcd9', 'name')                          AS trial_icd9_name,
                   parse_ps_udf(trialtherapeuticareas, 'trialIcd10', 'icd10Id')                      AS icd10id,
                   parse_ps_udf(trialtherapeuticareas, 'trialIcd10', 'name')                         AS trialicd10_name,
                   parse_ps_udf(trialtherapeuticareas, 'trialSnomed', 'snomedId')                    AS trial_snomed_id,
                   parse_ps_udf(trialtherapeuticareas, 'trialSnomed', 'name')                        AS trial_snomed_name,
        trialobjective                                                                    AS objective,
        concat_ws('| ', trialnotes.date)                                                  AS trial_date,
        concat_ws('| ', trialnotes.details)                                               AS trial_notes,
        trialinclusioncriteria                                                            AS inclusion_criteria,
        trialexclusioncriteria                                                            AS exclusion_criteria,
        parse_pe(trialprimaryendpoint,'primaryEndpoints','primaryEndpoint')               AS primary_endpoint,
        parse_pe(trialotherendpoint,'otherEndpoints','otherEndpoint')                     AS other_endpoint,
        trialstudydesign                                                                  AS study_design,
        concat_ws('| ', trialstudykeywords)                                               AS study_keywords,
        trialpatientpopulation                                                            AS patient_population_criteria,
        parse_protocolid(trialprotocolids)                                                     AS protocol_ids,
        parse_nctid(trialprotocolids)                                                     AS nct_id,
        get_eudract_number(trialprotocolids)                                                     AS eudract_number,
        concat_ws('| ', trialsponsors.NAME)                                               AS sponsor_name,
        concat_ws('| ', trialsponsors.type)                                               AS sponsor_type,
        concat_ws('| ', trialprimarydrugstested.drugid)                                   AS primary_drug_id,
        concat_ws('| ', trialprimarydrugstested.drugnameid)                               AS primary_drug_name_id,
        concat_ws('| ', trialprimarydrugstested.drugname)                                 AS primary_tested_drug_name,
        concat_ws('| ', trialprimarydrugstested.drugprimaryname)                          AS primary_drug_name,
        concat_ws('| ', trialprimarydrugstested.drugapprovalstatus)                       AS primary_drug_approval_status,
        parse_arrs_udf(trialprimarydrugstested.drugnames)                                 AS primary_drug_names,
        parse_arrs_udf(trialPrimaryDrugsTested.drugparentnames)                           AS other_primary_tested_parent_names,
        parse_arrs_udf(trialprimarydrugstested.drugtherapeuticclasses)                    AS trial_therapeutic_classes,
        parse_arrs_udf(trialprimarydrugstested.drugtherapeuticclasssynonyms)              AS drug_therapeutic_class_synonyms,
        parse_dm_udf(trialprimarydrugstested.mechanismsofaction, 'directMechanism')       AS mechanism_of_action,
        parse_dm_udf(trialprimarydrugstested.mechanismsofaction, 'mechanismSynonyms')     AS mechanism_synonyms,
        concat_ws('| ',trialotherdrugstested.drugnameid )                                 AS other_drug_name_id,
        concat_ws('| ',trialotherdrugstested.drugname )                                   AS other_drug_name,
        parse_arrs_udf(trialotherdrugstested.drugnames)                                   AS other_drug_names,
        parse_arrs_udf(trialotherdrugstested.drugparentnames)                             AS other_drug_tested_parentnames,
        trialpriorconcurrenttherapy                                                       AS trial_prior_concurrent_therapy,
        concat_ws('| ', trialresults.date)                                                AS results_date,
        concat_ws('| ', trialresults.details)                                             AS results_details,
        parse_arrs_udf(trialinvestigators)                                                AS trialinvestigators,
        trialtargetaccrual                                                                AS target_accrual,
        trialtargetaccrualtext                                                            AS trial_target_accrual_text,
        trialactualaccrual                                                                AS trial_actual_accrual,
        trialactualaccrualtext                                                            AS actual_accrual_text,
        trialprimaryendpointsreported                                                     AS trial_primary_endpoints_reported,
        trialidentifiedsites                                                              AS trial_identified_sites,
        trialreportedsites                                                                AS trial_reported_sites,
        concat_ws('| ',trialsupportingurls)                                               AS trial_supporting_urls,
        concat_ws('| ', trialoutcomes)                                                    AS trial_outcomes,
        trialoutcomedetails                                                               AS trial_outcome_details,
        trialpatientcriteria.minage                                                       AS min_patient_age,
        trialpatientcriteria.maxage                                                       AS max_patient_age,
        trialpatientcriteria.minageunits                                                  AS min_age_units,
        trialpatientcriteria.maxageunits                                                  AS max_age_units,
        trialpatientcriteria.gender                                                       AS patient_gender,
        concat_ws('| ', trialtags)                                                        AS trial_tags,
        triallastmodifieddate                                                             AS last_modified_date,
        concat_ws('| ',trialpatientdispositions )                                         AS trial_patient_dispositions,
        concat_ws('| ', trialassociatedcro)                                               AS trial_associated_cro,
        concat_ws('| ', trialctgovmeshterms)                                              AS trial_ct_gov_mesh_terms,
        copyrightnotice                                                                   AS copy_right_notice,
        recordurl                                                                         AS record_url,
        trialtreatmentplan                                                                AS trial_treatment_plan,
        trialsource                                                                       AS trial_source,
        trialtiming.actualtrialstartdate                                                  AS actual_trial_start_date,
        trialtiming.actualenrollmentduration                                              AS enrollment_duration,
        trialtiming.anticipatedenrollmentperiodclosedate                                  AS enrollment_close_date,
        trialtiming.actualtreatmentduration                                               AS treatment_duration,
        trialtiming.actualprimarycompletiondate                                           AS actual_primary_completion_date,
        trialtiming.totaltrialduration                                                    AS total_trial_duration,
        trialpatientspersitepermonth                                                      AS trial_patients_per_site_per_month,
        concat_ws('| ', trialprimarydrugstested.drugname)                                 AS drug_name,
        trialreportedsites                                                                AS number_of_sites,
        trialprimaryendpoint.details                                                      AS primary_endpoint_details,
        parse_pe(trialprimaryendpoint,'primaryEndpoints','primaryEndpointGroup')          AS primary_endpoint_group,
        parse_pe(trialprimaryendpoint,'primaryEndpoints','primaryEndpointSubGroup')       AS primary_endpoint_sub_group,
        trialotherendpoint.details                                                        AS other_endpoint_details,
        parse_pe(trialotherendpoint,'otherEndpoints','otherEndpointGroup')                AS other_endpoint_group,
        parse_pe(trialotherendpoint,'otherEndpoints','otherEndpointSubGroup')             AS other_endpoint_sub_group,
        concat_ws('| ', trialinvestigators)                                               AS investigators,
        trialtiming.actualtrialstartdate                                                  AS actual_start_date,
        '$$disease_area$$' as disease_area_name,
        `$type`                                                                           AS type,
        cast("{current_ts}" AS string)                                                    AS load_timestamp
FROM   $$table$$
