select
       concat_ws('; ', organizationTrials.id) as site_trial_id,
       concat_ws('; ', organizationTrials.trialPhase) as site_trial_phase,
       concat_ws('; ', organizationTrials.trialStatus) as site_trial_status,
       concat_ws('; ', organizationTrials.trialStartDate) as site_trial_start_date,
       concat_ws('; ', organizationPhoneNumbers) as site_phone_no,
       concat_ws('; ', organizationTrialInvestigators.investigatorId) as investigator_id,
       double_nested_list(organizationTrialInvestigators.trialId) as trials_under_investigator,
       organizationId as site_id,
       organizationTotalPastTrials as site_past_trials_total,
       organizationTotalTrials as site_trials_total,
       organizationName as site_name,
       concat_ws('; ', organizationSupportingUrls) as site_supporting_urls,
       concat_ws('; ', pastTrials) as past_trial_id_list,
       concat_ws('; ', organizationPrimaryInvestigators) as site_primary_investigators_id_list,
       organizationLocation.city as site_location_city,
       organizationLocation.streetAddress as site_location_street,
       organizationLocation.country as site_location_country,
       organizationLocation.state as site_location_state,
       organizationLocation.postcode as site_location_postcode,
       `$type` as type,
       organizationLastTrialStartDate as site_last_trial_start_date,
       concat_ws('; ', ongoingTrials) as site_current_trials_list,
       concat_ws('; ', organizationFaxNumbers) as site_fax_number,
       organizationCountryName as site_country,
       organizationType as site_type,
       concat_ws('; ', organizationRegions) as site_regions,
       concat_ws('; ', organizationAffiliatedInvestigators) as site_affiliated_investigators,
       concat_ws('; ', diseaseHierarchy) as disease_hierarchy,
       concat_ws('; ', organizationDiseaseTypes.name) as site_disease_type_name,
       concat_ws('; ', organizationDiseaseTypes.pastTrials) as site_past_trials_by_disease,
       concat_ws('; ', organizationDiseaseTypes.TotalTrials) as site_total_trials_by_disease,
       organizationTotalOngoingTrials as site_total_ongoing_trials,
       organizationGeoLocation.lat as site_geo_location_lat,
       organizationGeoLocation.lon as site_geo_location_lon,
       copyrightNotice as copyright_notice,
       recordUrl as record_url
 from $$table$$
