SELECT
	`$type`                                                         AS type,
	copyrightNotice                                                 AS copyright_notice,
	recordUrl 														AS record_url,
	companyId 														AS company_id,
	companyName 													AS company_name,
	companySymbol 													AS company_symbol,
	companyStockExchange 											AS company_stock_exchange,
	companyAddress1 												AS company_address1,
	companyAddress2 												AS company_address2,
	companyCountry 													AS company_country,
	companyState 													AS company_state,
	companyCity 													AS company_city,
	companyPostalCode 												AS company_postal_code,
	companyTelephone 												AS company_telephone,
	companyWebsite 													AS company_website,
	companySummary 													AS company_summary,
	subsidiaryActivity 												AS subsidiary_activity,
	researchFocus 													AS research_focus,
	concat_ws('|', financials.date) 								AS financials_date,
	concat_ws('|', financials.revenueUsd) 							AS financials_revenue_usd,
	concat_ws('|', financials.rndSpendUsd) 							AS financials_rnd_spend_usd,
	companyEmployees 												AS company_employees,
	yearEstablished 												AS year_established,
	ownershipType 													AS ownership_type,
	concat_ws('|', supportingURL) 									AS supporting_url,
	parentCompanyId 												AS parent_company_id,
	parentCompanyName 												AS parent_company_name,
	yearAcquired 													AS year_acquired
from $$table$$