DROP INDEX if exists ctfo_app_fa_prod.index_filter_country;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_trial_id_1;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_site_id;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_inv_id;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_trial_site_id;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_trial_site_inv_id;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_trial_inv_id;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_country_usa;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_country_code;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_region;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_trial_id_2;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_ta;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_dis;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_pat_seg;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_nct;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_phase;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_protocol;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_title;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_ta_dis_phase;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_ta_onc;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_trial_id_3;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_sponsor;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_drug;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_trial_status;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_drug_status;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_cas;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_gender;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_age;
DROP INDEX if exists ctfo_app_fa_prod.index_filter_mesh;
DROP INDEX if exists ctfo_app_fa_prod.index_site_study_trial_id;
DROP INDEX if exists ctfo_app_fa_prod.index_site_study_site_id;
DROP INDEX if exists ctfo_app_fa_prod.index_site_study_trial_site_id;
DROP INDEX if exists ctfo_app_fa_prod.index_site_study_trial_status;
DROP INDEX if exists ctfo_app_fa_prod.index_inv_site_study_trial_id;
DROP INDEX if exists ctfo_app_fa_prod.index_inv_site_study_site_id;
DROP INDEX if exists ctfo_app_fa_prod.index_inv_site_study_inv_id;
DROP INDEX if exists ctfo_app_fa_prod.index_inv_site_study_trial_site_id;
DROP INDEX if exists ctfo_app_fa_prod.index_inv_site_study_trial_inv_id;
DROP INDEX if exists ctfo_app_fa_prod.index_inv_site_study_trial_site_inv_id;
DROP INDEX if exists ctfo_app_fa_prod.index_country_country ;
DROP INDEX if exists ctfo_app_fa_prod.index_country_trial_id;
CREATE INDEX index_filter_country ON ctfo_app_fa_prod.f_rpt_filters_site_inv USING btree (country );
CREATE INDEX index_filter_trial_id_1 ON ctfo_app_fa_prod.f_rpt_filters_site_inv USING btree (ctfo_trial_id);
CREATE INDEX index_filter_site_id ON ctfo_app_fa_prod.f_rpt_filters_site_inv USING btree (ctfo_site_id );
CREATE INDEX index_filter_inv_id ON ctfo_app_fa_prod.f_rpt_filters_site_inv USING btree (ctfo_investigator_id);
CREATE INDEX index_filter_trial_site_id ON ctfo_app_fa_prod.f_rpt_filters_site_inv USING hash (trial_site_id);
CREATE INDEX index_filter_trial_site_inv_id ON ctfo_app_fa_prod.f_rpt_filters_site_inv USING hash (trial_site_inv_id);
CREATE INDEX index_filter_country_code ON ctfo_app_fa_prod.f_rpt_filters_site_inv USING btree (country_code );
CREATE INDEX index_filter_region ON ctfo_app_fa_prod.f_rpt_filters_site_inv USING btree (region );
CREATE INDEX index_filter_trial_inv_id ON ctfo_app_fa_prod.f_rpt_filters_site_inv USING btree (ctfo_investigator_id, ctfo_trial_id);
CREATE INDEX index_filter_country_usa ON ctfo_app_fa_prod.f_rpt_filters_site_inv (country) where country = 'United States';
CREATE INDEX index_filter_ta ON ctfo_app_fa_prod.f_rpt_filters_setup_all USING btree (therapeutic_area);
CREATE INDEX index_filter_dis ON ctfo_app_fa_prod.f_rpt_filters_setup_all USING btree (disease);
CREATE INDEX index_filter_phase ON ctfo_app_fa_prod.f_rpt_filters_setup_all USING btree (trial_phase);
CREATE INDEX index_filter_ta_dis_phase ON ctfo_app_fa_prod.f_rpt_filters_setup_all USING btree (therapeutic_area, disease, trial_phase);
CREATE INDEX index_filter_trial_id_2 ON ctfo_app_fa_prod.f_rpt_filters_setup_all USING btree (ctfo_trial_id);
CREATE INDEX index_filter_nct ON ctfo_app_fa_prod.f_rpt_filters_setup_all USING btree (nct_id);
CREATE INDEX index_filter_protocol ON ctfo_app_fa_prod.f_rpt_filters_setup_all USING btree (protocol_ids);
CREATE INDEX index_filter_title ON ctfo_app_fa_prod.f_rpt_filters_setup_all USING btree (study_name);
CREATE INDEX index_filter_pat_seg ON ctfo_app_fa_prod.f_rpt_filters_setup_all USING btree (patient_segment);
CREATE INDEX index_filter_ta_onc ON ctfo_app_fa_prod.f_rpt_filters_setup_all (therapeutic_area) where therapeutic_area = 'oncology';
CREATE INDEX index_filter_trial_id_3 ON ctfo_app_fa_prod.f_rpt_filters_trial USING btree (ctfo_trial_id);
CREATE INDEX index_filter_sponsor ON ctfo_app_fa_prod.f_rpt_filters_trial USING btree (sponsor);
CREATE INDEX index_filter_drug ON ctfo_app_fa_prod.f_rpt_filters_trial USING btree (drug_names);
CREATE INDEX index_filter_trial_status ON ctfo_app_fa_prod.f_rpt_filters_trial USING btree (trial_status);
CREATE INDEX index_filter_drug_status ON ctfo_app_fa_prod.f_rpt_filters_trial USING btree (drug_status);
CREATE INDEX index_filter_cas ON ctfo_app_fa_prod.f_rpt_filters_trial USING btree (cas_num);
CREATE INDEX index_filter_gender ON ctfo_app_fa_prod.f_rpt_filters_trial USING btree (gender);
CREATE INDEX index_filter_age ON ctfo_app_fa_prod.f_rpt_filters_trial USING btree (minimum_age, maximum_age);
CREATE INDEX index_filter_mesh ON ctfo_app_fa_prod.f_rpt_filters_trial USING btree (mesh_term);
CREATE INDEX index_site_study_trial_id ON ctfo_app_fa_prod.f_rpt_site_study_details USING btree (ctfo_trial_id);
CREATE INDEX index_site_study_site_id ON ctfo_app_fa_prod.f_rpt_site_study_details USING btree (ctfo_site_id);
CREATE INDEX index_site_study_trial_site_id ON ctfo_app_fa_prod.f_rpt_site_study_details USING hash (trial_site_id);
CREATE INDEX index_site_study_trial_status ON ctfo_app_fa_prod.f_rpt_site_study_details USING btree (trial_status);
CREATE INDEX index_inv_site_study_trial_id ON ctfo_app_fa_prod.f_rpt_investigator_site_study_details USING btree (ctfo_trial_id);
CREATE INDEX index_inv_site_study_site_id ON ctfo_app_fa_prod.f_rpt_investigator_site_study_details USING btree (ctfo_site_id);
CREATE INDEX index_inv_site_study_inv_id ON ctfo_app_fa_prod.f_rpt_investigator_site_study_details USING btree (ctfo_investigator_id);
CREATE INDEX index_inv_site_study_trial_site_id ON ctfo_app_fa_prod.f_rpt_investigator_site_study_details USING hash (trial_site_id);
CREATE INDEX index_inv_site_study_trial_inv_id ON ctfo_app_fa_prod.f_rpt_investigator_site_study_details USING btree (ctfo_investigator_id, ctfo_trial_id);
CREATE INDEX index_inv_site_study_trial_site_inv_id ON ctfo_app_fa_prod.f_rpt_investigator_site_study_details USING hash (trial_site_inv_id);
CREATE INDEX index_country_country ON ctfo_app_fa_prod.f_rpt_country USING hash (country);
CREATE INDEX index_country_trial_id ON ctfo_app_fa_prod.f_rpt_country USING hash (ctfo_trial_id);


vacuum analyze ctfo_app_fa_prod.f_rpt_filters_site_inv;
vacuum analyze ctfo_app_fa_prod.f_rpt_filters_setup_all;
vacuum analyze ctfo_app_fa_prod.f_rpt_filters_trial;
vacuum analyze ctfo_app_fa_prod.f_rpt_site_study_details;
vacuum analyze ctfo_app_fa_prod.f_rpt_investigator_site_study_details;
vacuum analyze ctfo_app_fa_prod.f_rpt_country;


